"""signup_final

Revision ID: 1d883a5cac6f
Revises: 7f0ce459725a
Create Date: 2026-04-09 09:45:49.467028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d883a5cac6f'
down_revision: Union[str, Sequence[str], None] = '7f0ce459725a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS doctors;")
    op.execute("DROP TABLE IF EXISTS patients;")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS doc_id INTEGER;")
    # op.execute("ALTER TABLE users ADD CONSTRAINT IF NOT EXISTS fk_users_doc_id FOREIGN KEY (doc_id) REFERENCES users (id) ON DELETE SET NULL;")
    # op.add_column('users', sa.Column('doc_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'users', 'users', ['doc_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'doc_id')
    op.create_table('patients',
    sa.Column('patient_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('their_doc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['their_doc'], ['doctors.doctor_id'], name=op.f('patients_their_doc_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('patients_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_id', name=op.f('patients_pkey'))
    )
    op.create_table('doctors',
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('doctors_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doctor_id', name=op.f('doctors_pkey'))
    )
    # ### end Alembic commands ###
