"""signup_sync

Revision ID: 35287641ea74
Revises: 8e92f95977f5
Create Date: 2026-04-08 11:04:18.225166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35287641ea74'
down_revision: Union[str, Sequence[str], None] = '8e92f95977f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # This autogenerated migration duplicated the schema already produced by
    # 730d7e9cb3ac and 8e92f95977f5. Keep the revision for Alembic history,
    # but do not recreate existing tables.
    pass


def downgrade() -> None:
    """Downgrade schema."""
    pass
