"""final_signupv2

Revision ID: 4c60f7ed8a22
Revises: 7fd7fb6244e3
Create Date: 2026-04-09 10:19:26.759948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c60f7ed8a22'
down_revision: Union[str, Sequence[str], None] = '7fd7fb6244e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('emergency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'emergencys', ['emergency_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'emergency_id')
    # ### end Alembic commands ###
