"""updated patient table

Revision ID: 7f0ce459725a
Revises: 8851b3b5ab48
Create Date: 2026-04-08 14:56:02.636952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0ce459725a'
down_revision: Union[str, Sequence[str], None] = '8851b3b5ab48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # This old autogenerated migration attempted to add a temporary
    # patients.their_doc -> doctors.doctor_id relationship. A later migration
    # removes the legacy doctors/patients tables and stores assignment on
    # users.doc_id, which is what the current app uses.
    pass


def downgrade() -> None:
    """Downgrade schema."""
    pass
