"""updated patient table

Revision ID: 7f0ce459725a
Revises: 8851b3b5ab48
Create Date: 2026-04-08 14:56:02.636952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0ce459725a'
down_revision: Union[str, Sequence[str], None] = '8851b3b5ab48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('their_doc', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patients', 'doctors', ['their_doc'], ['doctor_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'their_doc')
    # ### end Alembic commands ###
