"""sync-updated

Revision ID: 8e92f95977f5
Revises: 730d7e9cb3ac
Create Date: 2026-04-08 10:50:11.486433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e92f95977f5'
down_revision: Union[str, Sequence[str], None] = '730d7e9cb3ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.drop_constraint(op.f('contacts_phone_key'), 'contacts', type_='unique')
    op.drop_constraint(op.f('users_emergency_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_doctor_id_fkey'), 'users', type_='foreignkey')
    op.add_column('doctors', sa.Column('doctor_id', sa.Integer(), nullable=False))
    op.add_column('doctors', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('doctors_email_key'), 'doctors', type_='unique')
    op.drop_constraint(op.f('doctors_name_key'), 'doctors', type_='unique')
    op.create_foreign_key(None, 'doctors', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('doctors', 'phone_number')
    op.drop_column('doctors', 'email')
    op.drop_column('doctors', 'name')
    op.drop_column('doctors', 'id')
    op.drop_constraint(op.f('emergencys_email_key'), 'emergencys', type_='unique')
    op.drop_constraint(op.f('emergencys_name_key'), 'emergencys', type_='unique')
    op.alter_column('reminders', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'doctor_id')
    op.drop_column('users', 'emergency_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('emergency_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_doctor_id_fkey'), 'users', 'doctors', ['doctor_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('users_emergency_id_fkey'), 'users', 'emergencys', ['emergency_id'], ['id'], ondelete='CASCADE')
    op.alter_column('reminders', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(op.f('emergencys_name_key'), 'emergencys', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('emergencys_email_key'), 'emergencys', ['email'], postgresql_nulls_not_distinct=False)
    op.add_column('doctors', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('doctors', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('doctors', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('doctors', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.create_unique_constraint(op.f('doctors_name_key'), 'doctors', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('doctors_email_key'), 'doctors', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('doctors', 'user_id')
    op.drop_column('doctors', 'doctor_id')
    op.create_unique_constraint(op.f('contacts_phone_key'), 'contacts', ['phone'], postgresql_nulls_not_distinct=False)
    op.drop_table('patients')
    # ### end Alembic commands ###
