"""Appointment

Revision ID: ecbbab1dbf62
Revises: 54fb54a21372
Create Date: 2026-04-09 13:53:38.347067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecbbab1dbf62'
down_revision: Union[str, Sequence[str], None] = '54fb54a21372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('doctor_id', sa.Integer(), nullable=False))
    op.add_column('appointments', sa.Column('patient_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('appointments_doc_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'users', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'users', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_column('appointments', 'doc_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('doc_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_doc_id_fkey'), 'appointments', 'users', ['doc_id'], ['id'], ondelete='CASCADE')
    op.drop_column('appointments', 'patient_id')
    op.drop_column('appointments', 'doctor_id')
    # ### end Alembic commands ###
